Petstagram/Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('common.urls')),
                  path('pets/', include('pets.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram/common/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page, name='landing'),
]

Petstagram/pets/urls.py
from django.urls import path

from pets.views import pet_list, pet_detail, pet_like, pet_create, pet_edit, pet_delete

urlpatterns = [
    path('', pet_list, name='pet_list'),
    path('detail/<int:pk>/', pet_detail, name='pet_detail'),
    path('like/<int:pk>/', pet_like, name='pet_like'),
    path('create/', pet_create, name='create_pet'),
    path('edit/<int:pk>/', pet_edit, name='edit_pet'),
    path('delete/<int:pk>/', pet_delete, name='delete_pet'),
]

Petstagram/common/models.py
from django.db import models

from pets.models import Pet


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)

Petstagram/pets/models.py
from django.db import models


class Pet(models.Model):
    DOG = 'dog'
    CAT = 'cat'
    PARROT = 'parrot'
    UNKNOWN = 'unknown'

    PET_TYPES = (
        (DOG, 'Dog'),
        (CAT, 'Cat'),
        (PARROT, 'Parrot'),
        (UNKNOWN, 'Unknown'),
    )

    type = models.CharField(max_length=7, choices=PET_TYPES, default=UNKNOWN)
    name = models.CharField(max_length=6, blank=False)
    age = models.IntegerField(blank=False)
    description = models.TextField(blank=False)
    image = models.ImageField(upload_to='pets')


class Like(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

Petstagram/pets/forms/comment_form.py
from django import forms

from common.models import Comment


class CommentForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control rounded-2',
            }
        )
    )

Petstagram/pets/forms/pet_form.py
from django import forms

from pets.models import Pet


class PetForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Pet
        fields = '__all__'
        widgets = {
            'image_url': forms.TextInput(
                attrs={
                    'id': 'img_input',
                }
            )
        }

Petstagram/common/views.py
from django.shortcuts import render


def landing_page(request):
    return render(request, 'landing_page.html')

Petstagram/pets/views.py
from django.shortcuts import render, redirect

from common.models import Comment
from .forms.comment_form import CommentForm
from .forms.pet_form import PetForm
from .models import Pet, Like


def pet_list(request):
    context = {
        'pets': Pet.objects.all()
    }

    return render(request, 'pet_list.html', context)


def pet_detail(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.method == 'GET':
        context = {
            'pet': pet,
            'form': CommentForm(),
        }

        return render(request, 'pet_detail.html', context)
    else:
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = Comment(text=form.cleaned_data['text'])
            comment.pet = pet
            comment.save()

            return redirect('pet_detail', pk)

        context = {
            'pet': pet,
            'form': form,
        }

        return render(request, 'pet_detail.html', context)


def persist_pet(request, pet, template):
    if request.method == 'GET':
        form = PetForm(instance=pet)

        context = {
            'form': form,
            'pet': pet,
        }
        return render(request, f'{template}.html', context)
    else:
        form = PetForm(request.POST, request.FILES, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('pet_detail', pet.pk)

        context = {

            'form': form,
            'pet': pet,
        }

        return redirect(request, f'{template}.html', context)


def pet_create(request):
    pet = Pet()
    return persist_pet(request, pet, 'pet_create')


def pet_edit(request, pk):
    pet = Pet.objects.get(pk=pk)
    return persist_pet(request, pet, 'pet_edit')


def pet_delete(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.method == 'GET':
        context = {
            'pet': pet
        }
        return render(request, 'pet_delete.html', context)
    else:
        pet.delete()
        return redirect('pet_list')


def pet_like(request, pk):
    pet = Pet.objects.get(pk=pk)
    like = Like()
    like.pet = pet
    like.save()

    return redirect('pet_detail', pk)

Petstagram/templates/landing_page.html
{% extends 'site.html' %}
{% block content %}
    <div class="jumbotron parent">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="absolute">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="inner cover">
                <h1 class="cover-heading"></h1>
                <div class="row">
                    <div class="col-lg-6">
                        <p class="lead">Already have an account? <br><a href="#" class="btn btn-lg btn-secondary">sign
                            in</a></p>
                    </div>
                    <div class="col-lg-6">
                        <p class="lead"> Do not have an account? <br>
                            <a href="#" class="btn btn-lg btn-secondary">sign up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Petstagram/templates/pet_create.html
{% extends 'site.html' %}
{% block content %}
    <h1 class="text-center">Add new pet photo</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="post" class="furniture-form" enctype="multipart/form-data">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Petstagram/templates/pet_delete.html
{% extends 'site.html' %}
{% block content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete {{ pet.name }}?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete_pet' pet.pk %}">
                        {% csrf_token %}
                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Petstagram/templates/pet_detail.html
{% extends 'site.html' %}
{% block content %}
    <div class="d-flex">
        <div class="d-inline p-2 w-50">
            <img src="{{ pet.image.url }}" class="w-50 rounded mx-auto d-block">
        </div>
        <div class="d-inline p-2 w-50">
            <div class="d-flex justify-content-between">
                <h5><u>Type:</u>{{ pet.type }}</h5>
                <h5><u>Name:</u>{{ pet.name }}</h5>
                <h5><u>Age:</u>{{ pet.age }}</h5>
            </div>
            <p class="mt-2">Description: {{ pet.description }}</p>
            <a href="{% url 'pet_like' pet.id %}"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
            <p class="mt-2">Likes: {{ pet.like_set.count }}</p>

            <a href="{% url 'edit_pet' pet.id %}" class="btn btn-success">Edit</a>
            <a href="{% url 'delete_pet' pet.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    <div class="d-block" style="background-color: #f1e3e3; padding:2%">
        {% if pet.comment_set.count > 0 %}
            {% for comment in pet.comment_set.all %}
                <div class="box">
                    <h5><em>{{ comment.text }}</em></h5>
                    <hr>
                </div>
            {% endfor %}
        {% else %}
            <div class="box">
                <h3>There are no comments for this pet. </h3>
            </div>
        {% endif %}
        <div class="box">
            <form method="post">
                {{ form }}
                {% csrf_token %}
                <button class="btn btn-primary mt-2" type="submit">Add comment</button>
            </form>
        </div>
    </div>
{% endblock %}

Petstagram/templates/pet_edit.html
{% extends 'site.html' %}
{% block content %}
        <h1 class="text-center">Edit pet photo</h1>
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <form method="post" action="{% url 'edit_pet' pet.pk %}" class="furniture-form" enctype="multipart/form-data">
                    {{ form }}
                    {% csrf_token %}
                    <button class="btn btn-primary mt-2" type="submit">Edit</button>
                </form>
            </div>
            <div class="col-lg-3"></div>
        </div>
{% endblock %}

Petstagram/templates/pet_list.html
{% extends 'site.html' %}
{% block content %}
    <h1 class='text-center'>All pet photos</h1>
    <div class="row">
    {% for pet in pets %}
        <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
                <img src="{{ pet.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</h5>
                    <p class="card-text">{{ pet.description }}</p>
                    <a href="{% url 'pet_detail' pet.id %}" class="btn btn-primary">See details</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

Petstagram/templates/site.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <a class="nav-link" href="/">Home</a>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pet_list' %}">All Pet Photos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_pet' %}">Create Pet</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Sign Up</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>
</body>
</html>